disabled_rules: # 실행에서 제외할 규칙들
- trailing_whitespace # 라인 뒤에 공백 없어야함
- identifier_name # https://realm.github.io/SwiftLint/identifier_name.html
- type_name # https://realm.github.io/SwiftLint/type_name.html
- shorthand_operator # https://realm.github.io/SwiftLint/shorthand_operator.html
- line_length # https://realm.github.io/SwiftLint/line_length.html
- function_body_length # 함수 길이
- type_body_length # https://realm.github.io/SwiftLint/type_body_length.html
- cyclomatic_complexity # 복잡한 함수 X 리팩토링하면서 이 규칙은 나중에 활성해도 좋을듯


excluded:
- Hous-iOS-release/Application/AppDelegate.swift
- Hous-iOS-release/Application/SceneDelegate.swift
- "AssetKit"
- "BottomSheetKit"
- "UserInformation"
- "Network"
- "ThirdPartyLibraryManager"

force_cast: warning # 강제 캐스팅 경고
