disabled_rules: # 실행에서 제외할 규칙들
- cyclomatic_complexity # 복잡한 함수 X 리팩토링하면서 이 규칙은 나중에 활성해도 좋을듯
- closure_parameter_position # closure 인자 한줄에 변수 때문에 길어져서 적용 불가능
- function_body_length # 함수길이 40자 이상
- file_length # Code line 400줄 이상


excluded:
- Hous-iOS-release/Application/AppDelegate.swift
- Hous-iOS-release/Application/SceneDelegate.swift

# Repository
- Hous-iOS-release/Repository/User
- Hous-iOS-release/Repository/Onboarding
- Hous-iOS-release/Repository/Profile
- Hous-iOS-release/Repository/Todo

# Global
- Hous-iOS-release/Global/UIComponent/GraphBackgroundView.swift
- Hous-iOS-release/Global/UIComponent/GraphView.swift
- Hous-iOS-release/Global/UIComponent/QuitPopUpViewController.swift

# Extenstion
- Hous-iOS-release/Extension/CALayer+Extension.swift
- Hous-iOS-release/Extension/UIBezierPath+Extension.swift
- Hous-iOS-release/Extension/UIViewController+Rx.swift
- Hous-iOS-release/Extension/UIView+Extension.swift
- Hous-iOS-release/Extension/UIStackView+Extension.swift
- Hous-iOS-release/Extension/UITableView+Extension.swift
- Hous-iOS-release/Extension/ToastMessage.swift
- Hous-iOS-release/Extension/Reactive+Extension.swift
- Hous-iOS-release/Extension/UIDevice+Extension.swift
- Hous-iOS-release/Extension/UILabel+Extension.swift



- Hous-iOS-release/Scene/OurRule
- Hous-iOS-release/Scene/Onboarding
- Hous-iOS-release/Scene/MainHome
- Hous-iOS-release/Scene/Todo
- Hous-iOS-release/Scene/Profile
- Hous-iOS-release/Scene/TabBar



- "AssetKit"
- "BottomSheetKit"
- "UserInformation"
- "Network"
- "ThirdPartyLibraryManager"

