# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "ycmp-rrjw-swbl-pnrs"

platform :ios do
  
  # match 갱신 - git에 push (certificate, profile visioning)

  private_lane :renew_codesign do|options|
    match(type:options[:type], force_for_new_devices: true)
  end

  lane :renew_codesign_development do
    renew_codesign(type:"appstore")
    renew_codesign(type:"development")
  end

  lane :renew_codesign_staging do
    renew_codesign(type:"appstore")
    renew_codesign(type:"development")
  end

  lane :renew_codesign_release do
    renew_codesign(type:"appstore")
    renew_codesign(type:"development")
  end

  # match 로드 (certificate, profile visioning)

  private_lane :sync_codesign do|options|
    match(type:options[:type], readonly: true)
  end

  lane :sync_codesign_development do
    sync_codesign(type:"appstore")
    sync_codesign(type:"development")
  end

  lane :sync_codesign_staging do
    sync_codesign(type:"appstore")
    sync_codesign(type:"development")
  end

  lane :sync_codesign_release do
    sync_codesign(type:"appstore")
    sync_codesign(type:"development")
  end

  desc "Push a new beta build to TestFlight"
  lane :development do
    increment_build_number({
      xcodeproj: "./Hous-iOS-release.xcodeproj",
      build_number: latest_testflight_build_number(app_identifier: "com.hous.Hous-iOS-release.development") + 1
    })
    build_app(
        scheme: "Hous-iOS-release(Development)",
        output_directory: "./ipa"
    )
    upload_to_testflight(
    	skip_waiting_for_build_processing: true
    )
  end

  desc "Push a new release build to TestFlight"
  lane :production do
    increment_build_number({
      xcodeproj: "./Hous-iOS-release.xcodeproj",
      build_number: latest_testflight_build_number(app_identifier: "com.hous.Hous-iOS-release") + 1
    })
    build_app(
        scheme: "Hous-iOS-release",
        output_directory: "./ipa"
    )
    upload_to_app_store(
        submit_for_review: false,
        automatic_release: false,
        force: true,
        skip_screenshots: true,
        skip_metadata: true
    )
  end
end
